let path =require('path');

const DEFINE_PATH_NAME = {
  'BASE_DIRECTORY' : process.cwd(),
  'TOTAL_NAME' : "public",
  'STANDARD_ACCOUNT_NAME' : "standard",
  'ANONYMOUS_ACCOUNT_NAME' : "anonymous",
  'TEMPORARY_NAME' : "temporary"
}

const TOTAL_RESOURCE_PATH = path.join(DEFINE_PATH_NAME['BASE_DIRECTORY'], DEFINE_PATH_NAME['TOTAL_NAME']);

const STANDARD_ACCOUNT_PATH = path.join(TOTAL_RESOURCE_PATH, DEFINE_PATH_NAME['STANDARD_ACCOUNT_NAME']);
const ANONYMOUS_ACCOUNT_PATH = path.join(TOTAL_RESOURCE_PATH, DEFINE_PATH_NAME['ANONYMOUS_ACCOUNT_NAME']);
const TEM_RESOURCE_PATH = path.join(TOTAL_RESOURCE_PATH, DEFINE_PATH_NAME['TEMPORARY_NAME']);

module.exports = {
  DEFINE_PATH_NAME,
  TOTAL_RESOURCE_PATH,
  STANDARD_ACCOUNT_PATH,
  ANONYMOUS_ACCOUNT_PATH,
  TEM_RESOURCE_PATH
}
